version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-se
    environment:
      - POSTGRES_USER=se
      - POSTGRES_PASSWORD=se
      - POSTGRES_DB=se
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  app:
    depends_on:
      - postgres
    container_name: api-se
    image: maven:3.8.8-eclipse-temurin-17
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/se
      - SPRING_DATASOURCE_USERNAME=se
      - SPRING_DATASOURCE_PASSWORD=se
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - .:/app  # Faz merda mas é a vida
    command: sh -c "cd /app && mvn clean package -DskipTests && java -jar /app/target/se-0.0.1-SNAPSHOT.jar"

volumes:
  postgres-data:

networks:
  app-network:
