version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-se
    environment:
      - POSTGRES_USER=se
      - POSTGRES_PASSWORD=se
      - POSTGRES_DB=se
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'
    restart: always

  app:
    depends_on:
      - postgres
    container_name: api-se
    build:
      context: .
      dockerfile: Dockerfile
    image: se:v1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/se
      - SPRING_DATASOURCE_USERNAME=se
      - SPRING_DATASOURCE_PASSWORD=se
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - ./src:/app/src  # Mapeia o diretório src local para o contêiner
      - ./pom.xml:/app/pom.xml  # Mapeia o arquivo pom.xml local para o contêiner

volumes:
  postgres-data:

networks:
  app-network:
