spring:
  application:
    name: se
  datasource:
    url: jdbc:postgresql://172.21.0.2:5432/se
    username: se
    password: se
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hikari:
    minimum-idle: 5
    idle-timeout: 30000
    maximum-pool-size: 10
    auto-commit: false
    pool-name: MyHikariCP
    max-lifetime: 2000000
    connection-timeout: 30000
  server:
    error:
      include-message: always
  logging:
    pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet: DEBUG
